### ISSUE TITLE
panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

### ISSUE THREAD

**Issue by maratori** [ckaznocha/intrange#16]
The linter panics on the following code
```go
func Example(service protoreflect.ServiceDescriptor) {
	for i := 0; i < service.Methods().Len(); i++ {
		print(i)
	}
}
```

```
panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

goroutine 70 [running]:
github.com/ckaznocha/intrange.findNExpr({0x138cfc8?, 0xc000216340?})
        external/gazelle~~go_deps~com_github_ckaznocha_intrange/intrange.go:237 +0x13a
github.com/ckaznocha/intrange.run.check.func1({0x138c4e0?, 0xc0002163c0})
        external/gazelle~~go_deps~com_github_ckaznocha_intrange/intrange.go:95 +0x1f4
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc000010228, {0xc00022ed18?, 0x1538860?, 0xc000052908?}, 0xc00022ed08)
        external/gazelle~~go_deps~org_golang_x_tools/go/ast/inspector/inspector.go:82 +0x8f
github.com/ckaznocha/intrange.run(0xc0001a8270)
        external/gazelle~~go_deps~com_github_ckaznocha_intrange/intrange.go:47 +0x129
main.(*action).execOnce(0xc0001ade00)
        external/rules_go~/go/tools/builders/nogo_main.go:354 +0x8b7
sync.(*Once).doSlow(0x0?, 0xc000123200?)
        GOROOT/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        GOROOT/src/sync/once.go:65
main.(*action).exec(...)
        external/rules_go~/go/tools/builders/nogo_main.go:281
main.execAll.func1(0x0?)
        external/rules_go~/go/tools/builders/nogo_main.go:275 +0x72
created by main.execAll in goroutine 1
        external/rules_go~/go/tools/builders/nogo_main.go:273 +0x48
```

**Comment by ckaznocha** [comment]
Thanks for the report and thanks for sending over a PR!
